Updates the opm version and modifies the build-index-image script
* Makefile
 * Adds opm installation in the same manner as kustomize
 * Latest version supports http and skipping tls verification on unsecure
   registries

* action.yaml
 * Delegate fetching opm to the Makefile

* build-index-image.sh
 * Updates `opm render` to latest switches for opm version
 * Fixes for more reliable script execution

diff --git a/.github/actions/kamel-build-bundle/action.yaml b/.github/actions/kamel-build-bundle/action.yaml
--- a/.github/actions/kamel-build-bundle/action.yaml
+++ b/.github/actions/kamel-build-bundle/action.yaml
@@ -58,12 +58,11 @@ runs:
       name: Install opm if required
       shell: bash
       run: |
-        if ! command -v opm &> /dev/null
-        then
-          curl -L https://github.com/operator-framework/operator-registry/releases/download/v1.19.5/linux-amd64-opm -o opm
-          chmod +x opm
-          sudo mv opm /usr/local/bin/
-        fi
+        make opm
+
+        # Append to PATH if not already
+        echo "${{ env.GOPATH }}/bin" >> $GITHUB_PATH
+        which opm || { echo 'opm not found' ; exit 1; }
 
     - id: build-index-image
       name: Create New Index Image
