chore(e2e): install namespaced operator

diff --git a/.github/actions/e2e-install/action.yml b/.github/actions/e2e-install/action.yml
--- a/.github/actions/e2e-install/action.yml
+++ b/.github/actions/e2e-install/action.yml
@@ -15,8 +15,8 @@
 # limitations under the License.
 # ---------------------------------------------------------------------------
 
-name: e2e-install
-description: 'End-to-End tests for install use-cases (namespaced rather than global operator so no global operator install)'
+name: e2e-install-olm
+description: 'End-to-End tests for OLM installation and upgrade procedure'
 
 inputs:
   cluster-config-data:
@@ -35,11 +35,37 @@ runs:
     uses: ./.github/actions/kamel-prepare-env
 
   - id: config-cluster
-    name: Configure Platform
+    name: Configure Cluster
     uses: ./.github/actions/kamel-config-cluster
     with:
       cluster-config-data: ${{ inputs.cluster-config-data }}
       cluster-kube-config-data: ${{ inputs.cluster-kube-config-data }}
+      require-olm: true
+
+  - id: released-kamel-cli
+    name: Get Released Kamel CLI
+    shell: bash
+    run: |
+      export KAMEL_VERSION=$(make get-last-released-version)
+      curl -L https://github.com/apache/camel-k/releases/download/v${KAMEL_VERSION}/camel-k-client-${KAMEL_VERSION}-linux-amd64.tar.gz -o /tmp/kamel.tar.gz
+      pushd /tmp && tar -zxf kamel.tar.gz && popd > /dev/null
+      if [ ! -x /tmp/kamel ]; then
+        echo "Error: No ${KAMEL_VERSION} downloaded correctly"
+        exit 1
+      fi
+
+      #
+      # Note: cannot use GITHUB_ENV vars in same script as it was defined
+      #
+      export RELEASED_KAMEL_BINARY=/tmp/kamel-${KAMEL_VERSION}
+      mv /tmp/kamel ${RELEASED_KAMEL_BINARY}
+      if [ $? == 0 ]; then
+        echo "Info: Kamel version installed: $(${RELEASED_KAMEL_BINARY} version)"
+        echo "released-kamel-binary=${RELEASED_KAMEL_BINARY}" >> $GITHUB_OUTPUT
+      else
+        echo "Error: Failed to install kamel binary ${KAMEL_VERSION}"
+        exit 1
+      fi
 
   - id: build-kamel
     name: Build Kamel
@@ -48,23 +74,23 @@ runs:
       image-registry-push-host: ${{ steps.config-cluster.outputs.cluster-image-registry-push-host }}
       image-registry-pull-host: ${{ steps.config-cluster.outputs.cluster-image-registry-pull-host }}
       image-namespace: ${{ steps.config-cluster.outputs.cluster-image-namespace }}
-      # Builds the bundle if an OLM is available - depends on cluster being tested
+      # Builds the bundle if an OLM is available.
+      # Since configure-cluster requires OLM then this should be true
       build-bundle: ${{ steps.config-cluster.outputs.cluster-has-olm }}
       # Both can be empty and so catalog source will not be created
       catalog-source-name: ${{ steps.config-cluster.outputs.cluster-catalog-source-name }}
       catalog-source-namespace: ${{ steps.config-cluster.outputs.cluster-catalog-source-namespace }}
 
-  - id: run-it
-    name: Run IT
+  - name: Run IT
     shell: bash
     run: |
+      # Note different parameters due to alternative installation
       ./.github/actions/e2e-install/exec-tests.sh \
-        -b "${{ steps.config-cluster.outputs.cluster-catalog-source-name }}" \
-        -c "${{ steps.config-cluster.outputs.cluster-catalog-source-namespace }}" \
-        -i "${{ steps.config-cluster.outputs.cluster-image-namespace }}" \
+        -b "${{ steps.released-kamel-cli.outputs.released-kamel-binary }}" \
+        -d "${{ steps.build-kamel.outputs.build-bundle-image-bundle-index }}" \
         -l "${{ steps.config-cluster.outputs.cluster-image-registry-pull-host }}" \
         -n "${{ steps.build-kamel.outputs.build-binary-local-image-name }}" \
         -q "${{ env.CAMEL_K_LOG_LEVEL }}" \
-        -s "${{steps.config-cluster.outputs.cluster-image-registry-insecure }}" \
+        -s "${{ steps.config-cluster.outputs.cluster-image-registry-insecure }}" \
         -v "${{ steps.build-kamel.outputs.build-binary-local-image-version }}" \
         -x "${{ env.CAMEL_K_TEST_SAVE_FAILED_TEST_NAMESPACE }}"
