Fixes failure in OLM upgrade e2e tests
* Makefile
 * Updates LAST RELEASED VERSION to 1.6.1 as this is included in the
   released index image. 1.7.0 needs to replace this rather than 1.6.0
 * Adds pre-bundle rule for updating the CSV manifest prior to building
   the bundle

* actions
 * Adds more checking to ensure the action is performing as expected
 * Since replaces is added using Makefile, it is removed from here

* *.go
 * Converts uninstall command to a function which is then guaranteed to
   execute via a deferral

diff --git a/.github/workflows/upgrade.yml b/.github/workflows/upgrade.yml
--- a/.github/workflows/upgrade.yml
+++ b/.github/workflows/upgrade.yml
@@ -75,10 +75,19 @@ jobs:
       shell: bash
       run: |
         export KAMEL_VERSION=$(make get-last-released-version)
-        curl -L https://github.com/apache/camel-k/releases/download/v${KAMEL_VERSION}/camel-k-client-${KAMEL_VERSION}-linux-64bit.tar.gz -o kamel.tar.gz
-        tar -zxf kamel.tar.gz
-        sudo mv kamel /usr/local/bin/
-        echo "Kamel version installed: $(kamel version)"
+        curl -L https://github.com/apache/camel-k/releases/download/v${KAMEL_VERSION}/camel-k-client-${KAMEL_VERSION}-linux-64bit.tar.gz -o /tmp/kamel.tar.gz
+        pushd /tmp && tar -zxf kamel.tar.gz && popd > /dev/null
+        if [ ! -x /tmp/kamel ]; then
+          echo "ERROR: No ${KAMEL_VERSION} downloaded correctly"
+          exit 1
+        fi
+        sudo mv /tmp/kamel /usr/local/bin/
+        if [ $? == 0 ]; then
+          echo "Kamel version installed: $(kamel version)"
+        else
+          echo "ERROR: Failed to install kamel binary ${KAMEL_VERSION}"
+          exit 1
+        fi
 
     - id: build-kamel-binary
       name: Build Kamel Binary
